# Generated by Django 4.0.3 on 2022-05-04 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_residente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_placa', models.CharField(max_length=50, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('tipo_residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo2', to='app_cobro.tipo_residente')),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo1', to='app_cobro.tipo_vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_ticker', models.CharField(max_length=255, unique=True)),
                ('isResidente', models.BooleanField(default=False)),
                ('hora_input', models.DateTimeField()),
                ('hora_output', models.DateTimeField()),
                ('no_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cobro.caja')),
                ('no_placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticker', to='app_cobro.vehiculo')),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_ticker', to='app_cobro.tarifa')),
            ],
        ),
        migrations.AddField(
            model_name='tarifa',
            name='tipo_residente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldo_tipo2', to='app_cobro.tipo_residente'),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='tipo_vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldo_tipo1', to='app_cobro.tipo_vehiculo'),
        ),
    ]
