# Generated by Django 4.0.3 on 2022-05-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cobro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='isParking',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='hora_input',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='hora_output',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
