# Generated by Django 4.0.3 on 2022-05-11 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_vehiculo', '0001_initial'),
        ('app_cobro', '0002_ticker_isparking_alter_ticker_hora_input_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='tipo_residente',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='tipo_vehiculo',
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='tipo_residente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldo_tipo2', to='app_vehiculo.tipo_residente'),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='tipo_vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldo_tipo1', to='app_vehiculo.tipo_vehiculo'),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='no_placa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticker', to='app_vehiculo.vehiculo'),
        ),
        migrations.DeleteModel(
            name='Tipo_residente',
        ),
        migrations.DeleteModel(
            name='Tipo_vehiculo',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
