# Generated by Django 4.0.3 on 2022-05-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='descripcion',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
